/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HomeContact: typeof import('./src/components/home/HomeContact.vue')['default']
    HomeDownload: typeof import('./src/components/home/HomeDownload.vue')['default']
    HomeHospital: typeof import('./src/components/home/HomeHospital.vue')['default']
    HomeIntro: typeof import('./src/components/home/HomeIntro.vue')['default']
    HomeNews: typeof import('./src/components/home/HomeNews.vue')['default']
    HomeRecruiting: typeof import('./src/components/home/HomeRecruiting.vue')['default']
    HomeTeam: typeof import('./src/components/home/HomeTeam.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheBanner: typeof import('./src/components/TheBanner.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheLayout: typeof import('./src/components/TheLayout.vue')['default']
    TheMenu: typeof import('./src/components/TheMenu.vue')['default']
  }
}
